### ISSUE TITLE
GuideCaseQueue给队列设置动画会一直卡在第一个step1

### ISSUE THREAD

**Issue by wangjing71** [xuexiangjys/XUI#103]
**问题描述（必填）**
GuideCaseQueue一直卡在第一个step1

**使用的XUI版本（必填）**
1.1.6

**如何重现（必填）**
重现的步骤:
创建引导队列如果给每个队列设置进入和退出动画 会卡在第一个step
取消设置动画的代码则正常
                .enterAnimation(enterAnimation)
                .exitAnimation(exitAnimation)

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/16797781/117753427-0b7d8980-b24b-11eb-91a9-2b243bf2826a.png)
![image](https://user-images.githubusercontent.com/16797781/117753462-19330f00-b24b-11eb-87cb-820fbd4cd379.png)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: 华为mate30 5G]
 - Android版本: [Android 10]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**Comment by wangjing71** [comment]
可是不添加动画就是正常的。。。

**Comment by xuexiangjys** [comment]
那是因为你动画用的不对啊!你有仔细看demo演示了吗?
退出动画的监听是需要在onAnimationEnd的地方去removeView的,你不看怪谁呢?
