### ISSUE TITLE
Android 5.1.1 部分组件无分割线条显示

### ISSUE THREAD

**Issue by Deepx-China** [xuexiangjys/XUI#108]
**问题描述（必填）**

我是直接跑的demo
Android 5.1.1 目前已使用的组件有： tabbar、通用布局->XUIGroupListView 无分割线条显示

**使用的XUI版本（必填）**

implementation 'com.github.xuexiangjys:XUI:1.1.7'

**期望的效果**

期望在5.1.1中能实现与其他版本如7.1一致的效果

**截图**
![Screenshot_2021-06-21-15-38-30](https://user-images.githubusercontent.com/20198428/122726611-c2d4d980-d2a8-11eb-8619-87c09d4a651c.png)
![Screenshot_2021-06-21-15-38-50](https://user-images.githubusercontent.com/20198428/122726619-c4060680-d2a8-11eb-942c-b75667b69d52.png)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: 手持终端设备（i6300A）
 - Android版本: Android 5.1.1

**Comment by xuexiangjys** [comment]
我怀疑和android的版本无关, 和你使用的手机rom有关系

**Comment by xuexiangjys** [comment]
我使用的Android5.1.1的模拟器是正常的

**Comment by Deepx-China** [comment]
> 我怀疑和android的版本无关, 和你使用的手机rom有关系

好吧
