### ISSUE TITLE
MaterialSpinner 使用自定义adapter是当前选中显示内容错误

### ISSUE THREAD

**Issue by har-up** [xuexiangjys/XUI#109]
**提Bug前需要做的事情**

**问题描述（必填）**
MaterialSpinner 使用自定义adapter是当前选中显示内容错误，显示的是文本是对象的toString

**使用的XUI版本（必填）**
1.1.7

**如何重现（必填）**
重现的步骤:

**期望的效果**

**截图**

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
就是显示对象的toString内容，不然显示什么呢？你不会重写一下toString方法吗？为这个还要加一个接口合适吗？

**Comment by har-up** [comment]
你说的也行，但我觉得应该显示的是 adapter的getItemText（）
