### ISSUE TITLE
希望可以继承android最新的主题

### ISSUE THREAD

**Issue by xu2012** [xuexiangjys/XUI#110]
现在如果集成了XUI，在xml里使用MaterialButton就会报错

**Comment by xuexiangjys** [comment]
所有你的报错是什么呢?
还有这和Android最主题有什么关系呢?最新的主题又是什么呢?

**Comment by xu2012** [comment]
![image](https://user-images.githubusercontent.com/12170444/124537016-a78ed000-de4b-11eb-80f1-7db42e1cf8c9.png)
![image](https://user-images.githubusercontent.com/12170444/124537057-be352700-de4b-11eb-8cef-3ffba287a982.png)
不好意思哈，可能我没说清楚，因为我集成了XUI，然后又在项目里用Material主题的组件，所以编译就会报错，我意思是XUI后边可不可以兼容下Theme.MaterialComponents这个主题，现在AS新建的应用默认都是继承Theme.MaterialComponents这个主题
![image](https://user-images.githubusercontent.com/12170444/124537194-018f9580-de4c-11eb-9a53-46be3e951902.png)

**Comment by xuexiangjys** [comment]
你自己覆盖重写一下 XUIRootTheme主题试一下， 我这个UI框架是要向下兼容到Android17的，不可能使用这个主题作为根主题的
