### ISSUE TITLE
MaterialEditText的gravity属性失效

### ISSUE THREAD

**Issue by xiyangyang8110** [xuexiangjys/XUI#114]
<com.xuexiang.xui.widget.edittext.materialedittext.MaterialEditText
        android:id="@+id/etPassword"
        android:layout_width="@dimen/input_widht"
        android:layout_height="@dimen/input_height"
        android:gravity="center"
        android:hint="密码"
        android:inputType="textPassword"
        android:textSize="@dimen/defult_text_size"
        app:layout_constraintBottom_toBottomOf="@+id/input2"
        app:layout_constraintLeft_toLeftOf="@+id/input2"
        app:layout_constraintRight_toRightOf="@+id/input2"
        app:layout_constraintTop_toTopOf="@+id/input2"
        app:met_bottomTextSize="@dimen/defult_text_size"
        app:met_allowEmpty="false"
        app:met_errorEmpty="密码不能为空"
        app:met_hideUnderline="true"
        app:met_textColor="@color/white"
        android:visibility="invisible"
        />

已经设置 android:gravity="center"，实际运行到tv终端并没有居中

**Comment by xuexiangjys** [comment]
你还需要下面这个设置,因为框架中的输入框默认样式都是左对齐的
android:textAlignment="center"
