### ISSUE TITLE
activity的样式使用android:theme="@style/AppXuiTheme"后，activity布局中的系统控件EditText的gravity=end属性失效

### ISSUE THREAD

**Issue by jiapengtao** [xuexiangjys/XUI#118]
查看了XUI的源码，发现了这段代码
    <style name="EditTextBase" parent="android:Widget.Holo.Light.EditText">
        <item name="android:textAlignment">viewStart</item>
        <item name="android:gravity">start|center_vertical</item>
        <item name="android:textDirection">locale</item>
    </style>

测试后确认跟<item name="android:textAlignment">viewStart</item>这行代码有关，需要在EditText中手动将改属性android:textAlignment设置为viewEnd才行，这和正常使用系统控件时的习惯不一致，请问这个可以优化下吗？

**Comment by xuexiangjys** [comment]
没听懂你在说什么...

**Comment by xuexiangjys** [comment]
你如果不想让android:textAlignment生效,可以设置应用不支持rtl
或者全局重写android:editTextStyle主题属性,覆盖框架中的定义

**Comment by jiapengtao** [comment]
好的，谢谢
