### ISSUE TITLE
RecyclerView某些情况下滑动会消失不见

### ISSUE THREAD

**Issue by ywss** [xuexiangjys/XUI#123]
RecyclerView某些情况下滑动会消失不见，不需要滑动很快，慢慢滑动就行，项目高度什么的我都设置为固定了。

XUI 1.1.8版本

定位出和 com.scwang.smartrefresh.layout.adapter.SmartRecyclerAdapter 的动画有关

mOpenAnimationEnable 设为 false就好了

可能和这个方法内的alpha动画有关系
    private void addAnimate(SmartViewHolder holder, int position) {
        if (mOpenAnimationEnable && mLastPosition < position) {
            holder.itemView.setAlpha(0);
            holder.itemView.animate().alpha(1).start();
            mLastPosition = position;
        }
    }

怎么重现没有试出来，因为一般没问题。发现什么规律再汇报下

希望还是作者能修改下

**Comment by xuexiangjys** [comment]
请使用BaseRecyclerAdapter代替SmartRecyclerAdapter

**Comment by impl1874** [comment]
我也遇到了这个问题，记录下。

RecyclerView，一共20条数据，屏幕可显示6条，0-5条显示正常，后面的6-7两条不显示（空白），但高度正常，8到最后1条以后的又正常。

主要原因就是addAnimate存在污染复用组件的情况，增加一个else实现或者设置setOpenAnimationEnable(false)即可
