### ISSUE TITLE
AndroidX，Gradle是7.0.2，无法使用二维码控件_XQRCode，报错

### ISSUE THREAD

**Issue by zhoulongyaun** [xuexiangjys/XUI#125]
我在使用二维码控件_XQRCode时遇到了问题。
原来的项目gradle是5.4.1，可以使用。后来升级到7.0.2就无法使用了。引入没有问题，在编译的时候报错，报错如下：

`Manifest merger failed : android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
`
这是我build.gradle的配置：
![image](https://user-images.githubusercontent.com/42227354/142562832-af4cc842-d663-4c43-94d3-69327301fd51.png)
我在网上查到的是修改启动项 Activity，但是我已经修改了，还是有问题。
![image](https://user-images.githubusercontent.com/42227354/142562955-f86022e9-20f3-41f6-8006-4313411951bf.png)

望大佬指点一二。

**Comment by xuexiangjys** [comment]
把targetsdk降到30以下
