### ISSUE TITLE
MaterialEditText 的 floatingLabel 不想要半透明怎么办？

### ISSUE THREAD

**Issue by kvgnt** [xuexiangjys/XUI#130]
### Discussed in https://github.com/xuexiangjys/XUI/discussions/128

<div type='discussions-op-text'>

<sup>Originally posted by **kvgnt** December  8, 2021</sup>
floatingLabel 的半透明很影响操作体验，对一些弱视群体不友善，请问如何把半透明效果去掉。</div>
获取焦点跟失去焦点 label 变色已经足够体现区别了。希望加个开关去掉文字半透明效果。

**Comment by kvgnt** [comment]
[截图获取焦点跟失去焦点时的区别](https://imgtu.com/i/oz5DR1)

**Comment by xuexiangjys** [comment]
你自己修改源码使用吧,这是非常小众的需求
https://github.com/xuexiangjys/XUI/blob/master/xui_lib/src/main/java/com/xuexiang/xui/widget/edittext/materialedittext/MaterialEditText.java#L1613
把focusFraction去掉
```
            int alpha = ((int) ((floatingLabelAlwaysShown ? 1 : floatingLabelFraction) * 0xff * (0.74f * (isEnabled() ? 1 : 0) + 0.26f) * (floatingLabelTextColor != -1 ? 1 : Color.alpha(floatingLabelTextColor) / 255F)));

```
