### ISSUE TITLE
TimePickerView.setRangDate设置时间范围问题

### ISSUE THREAD

**Issue by duoluodesonger** [xuexiangjys/XUI#135]
**问题**
TimePickerView设置时间范围只精确到了年月日
**期望的效果**
希望时间范围精确到时分。

**Comment by xuexiangjys** [comment]
麻烦看明白了再写,有现成的方法,为什么不用?
https://github.com/xuexiangjys/XUI/blob/9f10d357a60c428ab36931a4841c5176d9b9502f/app/src/main/java/com/xuexiang/xuidemo/fragment/components/pickerview/TimePickerFragment.java#L131

**Comment by duoluodesonger** [comment]
我是说的设置选择时间范围setRangDate只能精确到年月日，比如我想选2022-5-23 08:00:00到2022-5-23 10:00:00

**Comment by duoluodesonger** [comment]
这样不行

**Comment by duoluodesonger** [comment]
@xuexiangjys  想选时间范围在时分秒

**Comment by duoluodesonger** [comment]
@xuexiangjys  一个时间点到另一个时间点精确到时分这种，不是显示时间到时分秒

**Comment by xuexiangjys** [comment]
请用组合的方式去实现
