### ISSUE TITLE
挺不错的 -建议

### ISSUE THREAD

**Issue by 1976222027** [xuexiangjys/XUI#14]
不是提交bug  我没看代码。只是简单体验了提下demo
是建议  侧滑抽屉 建议参考nineoldandroids-2.4.0.jar 
手滑可以唤出，主界面可以平移或覆盖、缩放
可以参考
https://img-blog.csdn.net/20160301213230619?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQv/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center

**Comment by xuexiangjys** [comment]
主界面我是故意禁掉动画动作的，至于原因为什么，你可以详细看代码
