### ISSUE TITLE
请问 openPageForResult 这个方法可以用在fragment之间跳转吗

### ISSUE THREAD

**Issue by chenyao1208** [xuexiangjys/XUI#140]
我尝试在fragment之间使用openPageForResult，但是似乎无法使用。
![image](https://user-images.githubusercontent.com/21217350/176071339-38046b45-3aba-420a-a0c3-4bfbdd2ca73b.png)

**Comment by xuexiangjys** [comment]
完全是可以的.
XPage的详细使用请参见官方文档和demo:https://github.com/xuexiangjys/XPage

**Comment by chenyao1208** [comment]
Xpage项目中没有真正使用到openPageForResult的页面，我在使用过程中发现在fragment之间用openPageResult会报错，烦请解答这个openPegeForResult应该是怎样使用的
