### ISSUE TITLE
XUI 控件 Android 2021.3.1预览问题

### ISSUE THREAD

**Issue by Miku06** [xuexiangjys/XUI#148]
**问题描述（必填）**
部分需要用到 context 的控件，在Android studio layout预览会报错 
“ java.lang.ExceptionInInitializerError: 请先在全局Application中调用 XUI.init() 初始化！”

**在2021.3.1 stable版本会导致整个渲染出现空白（可能也是AS IDE的bug）。
不影响编译，仅影响开发时候的预览。**

**使用的XUI版本（必填）**
1.1.9

**如何重现（必填）**
 任何layout 使用Supertextview 等控件

**期望的效果**
 是否可以考虑添加 View.isInEditMode() 判断来消除这些报错？

**截图**
![image](https://user-images.githubusercontent.com/9605145/192929067-6cfb0aca-9bda-4542-9bb5-10d43f280256.png)

**设备信息**
无
 

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by zlflying** [comment]
更新Android Studio后，今天刚打开我的项目也是报同样的错😭😭😭😭😭

**Comment by xuexiangjys** [comment]
14dce30e443c9a510038585ae531dc667230f1c0
已做修改,后续会发出一个新版本
