### ISSUE TITLE
TemplateAppProject 内存泄漏

### ISSUE THREAD

**Issue by 1980922803** [xuexiangjys/XUI#150]
[TemplateAppProject](https://gitee.com/xuexiangjys/TemplateAppProject)  Xtoast内存泄漏 怎么在这个项目上修改

**Comment by xuexiangjys** [comment]
6e1fe0ef4bbd08250650758633675e4fd8a47685

**Comment by 1980922803** [comment]
Type com.xuexiang.xui.widget.button.switchbutton.SwitchButton$1 is defined multiple times: E:\XHAppProject-master\app\build\intermediates\transforms\com.xuexiang.xrouter\debug\10.jar:com/xuexiang/xui/widget/button/switchbutton/SwitchButton$1.class, E:\XHAppProject-master\app\build\intermediates\transforms\com.xuexiang.xrouter\debug\113.jar:com/xuexiang/xui/widget/button/switchbutton/SwitchButton$1.class
