### ISSUE TITLE
MaterialDialog内存泄漏

### ISSUE THREAD

**Issue by chenxiaojin** [xuexiangjys/XUI#154]
**问题描述（必填）**
使用MaterialDialog时出现leaknary报内存泄漏

**使用的XUI版本（必填）**
1.2.0

**如何重现（必填）**
重现的步骤:
这是代码
```java
private fun showProjectChange() {
        MaterialDialog.Builder(this)
            .iconRes(R.mipmap.icon_tip)
            .title("提示")
            .content("项目变更，将会清除之前所有配置，是否变更项目")
            .positiveText("是")
            .onPositive { _, _ ->
                viewModel.changeProject()
            }
            .negativeText("否")
            .show()
    }
```
执行后弹框显示，点击“否”， 继续弹框，多次操作之后。 退出Activity后leaknary报内存泄漏

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - Android版本: Android 11
 - 设备型号 : RK3568

**Comment by xuexiangjys** [comment]
麻烦提供一下内存泄漏的日志

**Comment by chenxiaojin** [comment]
> 麻烦提供一下内存泄漏的日志

[leaknary日志.txt](https://github.com/xuexiangjys/XUI/files/10702778/leaknary.txt)

**Comment by xuexiangjys** [comment]
> > 麻烦提供一下内存泄漏的日志
> 
> [leaknary日志.txt](https://github.com/xuexiangjys/XUI/files/10702778/leaknary.txt)

我并不能复现出内存溢出,请确保屏幕是否发生了旋转

**Comment by chenxiaojin** [comment]
可能是我这边第三方包连带引起的内存泄漏。 这个问题我后面再分析，如果还有问题再请教， 多谢~
