### ISSUE TITLE
onCreate 多次创建的问题

### ISSUE THREAD

**Issue by ywss** [xuexiangjys/XUI#155]
**问题描述（必填）**
onCreate 多次创建

**使用的XUI版本（必填）**
XUI:1.2.0

**如何重现（必填）**
重现的步骤:
1. 将 compileSdk 和 targetSdk 都设置为 33 
2. 在 Application 类的 onCreate 里创建容器  PageConfig.getInstance()
                    .setContainActivityClazz(MainActivity.class) //设置默认的容器Activity
                    .init(this); 
3. MainActivity 的 onCreate 会被调用 2 次

**Comment by xuexiangjys** [comment]
没有哪个人会把`MainActivity.class`作为默认的空容器的.
请不要胡乱使用.

**Comment by ywss** [comment]
今天详细排查了下，是由于pad的旋转导致 activity 在启动时创建了两次造成的，并且只在compileSdk 和 targetSdk  33 版本上才发生，加了”android:configChanges="orientation|screenSize|screenLayout" 目前是可以了。
关于上面的用法是看了你的视频写的。没详细研究框架的代码，你的意思是这样用是不对的吗，具体应该怎么样改正呢？

**Comment by xuexiangjys** [comment]
> 今天详细排查了下，是由于pad的旋转导致 activity 在启动时创建了两次造成的，并且只在compileSdk 和 targetSdk 33 版本上才发生，加了”android:configChanges="orientation|screenSize|screenLayout" 目前是可以了。 关于上面的用法是看了你的视频写的。没详细研究框架的代码，你的意思是这样用是不对的吗，具体应该怎么样改正呢？

一般不需要设置默认容器, 框架是自带的, 除非是有特殊需求.
