### ISSUE TITLE
demo中下拉刷新样式item点击不生效

### ISSUE THREAD

**Issue by insvolc** [xuexiangjys/XUI#160]
**问题描述**
demo中下拉刷新样式item点击不生效

**如何重现**
demo中下拉刷新样式中的RefreshClassicsStyleFragment，RefreshAllStyleFragment，RefreshMaterialStyleFragment
里面的列表点击不生效

**设备信息**
vivo x90

**问题原因**
没有调用`adapter.setOnItemClickListener`导致列表点击不生效
将这3个Fragment中实现的接口从`SmartViewHolder.OnItemClickListener`改为`RecyclerViewHolder.OnItemClickListener`
然后调用`adapter.setOnItemClickListener`之后，列表item点击正常

**Comment by xuexiangjys** [comment]
已处理,之前修改adapter的时候漏掉了
