### ISSUE TITLE
SwitchButton的style不生效

### ISSUE THREAD

**Issue by acloudtwei** [xuexiangjys/XUI#164]
在使用SwitchButton控件时，使用style为"@style/SwitchButton"会爆红，默认找不到。

![image](https://github.com/xuexiangjys/XUI/assets/59042581/a0a2da51-bcb8-44ba-a6c2-6b7615552bc6)

**Comment by guodun123** [comment]
老哥你有没有遇到SuperTextView和MaterialEditText无法聚焦的问题

**Comment by acloudtwei** [comment]
有的，貌似这两个控件有点问题~

**Comment by guodun123** [comment]
解决了吗？？怎么解决的

**Comment by xuexiangjys** [comment]
有没有搞错, 框架本身就没有提供`@style/SwitchButton`, 当然找不到啦....
麻烦不要提这种无聊的问题...
