### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by baowenqing** [xuexiangjys/XUI#169]
A problem occurred configuring root project 'XUI'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.github.xuexiangjys.XAOP:xaop-plugin:1.1.0.
     Required by:
         project :
      > Could not resolve com.github.xuexiangjys.XAOP:xaop-plugin:1.1.0.
         > Could not get resource 'https://jitpack.io/com/github/xuexiangjys/XAOP/xaop-plugin/1.1.0/xaop-plugin-1.1.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/xuexiangjys/XAOP/xaop-plugin/1.1.0/xaop-plugin-1.1.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve com.github.xuexiangjys.XRouter:xrouter-plugin:1.0.1.

**Comment by xuexiangjys** [comment]
这个多试几次就行了, 要么是jitpack仓库不稳定,要么就是你的网络不稳定.

**Comment by hanqingkai** [comment]
我的也是这个问题，大佬解决了么
