### ISSUE TITLE
使用RoundButton时无发正常预览

### ISSUE THREAD

**Issue by hshande** [xuexiangjys/XUI#172]
![image](https://github.com/xuexiangjys/XUI/assets/17735478/e2aa0f0e-d521-4ef7-9264-d71f2c942e40)

**Comment by xuexiangjys** [comment]
正常xml的预览都需要编译通过才行.你无法预览,可能是你mei y没有进行编译,或者你的AS出问题了
<img width="981" alt="image" src="https://github.com/xuexiangjys/XUI/assets/15059629/2fc2b0ae-3f66-4c2f-9bb8-b6035a55dffd">
