### ISSUE TITLE
标题栏使用无效的问题

### ISSUE THREAD

**Issue by 1411862854** [xuexiangjys/XUI#174]
fragment页面xml：
`<?xml version="1.0" encoding="utf-8"?>

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="?attr/xui_config_color_background"
    android:orientation="vertical">

    <com.xuexiang.xui.widget.actionbar.TitleBar
        android:id="@+id/titlebar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:tb_actionPadding="20dp"
        app:tb_centerGravity="center"
        app:tb_titleText="这是一个Title"
        app:tb_useThemeColor="false"
        android:background="@color/app_color_theme_7"
        />
</LinearLayout>`
fragment页面class:
import com.xuexiang.xaop.annotation.SingleClick;
import com.xuexiang.xpage.annotation.Page;
import com.xuexiang.xpage.enums.CoreAnim;
import com.xuexiang.xui.utils.DensityUtils;
import com.xuexiang.xui.widget.actionbar.TitleBar;
import butterknife.BindView;
/**
 * @author xuexiang
 * @since 2019-10-30 00:19
 */
@Page(anim = CoreAnim.none)
public class NfcFragment extends BaseFragment {

    @BindView(R.id.titlebar)
    TitleBar mTitleBar;

    @NonNull
    @Override
    protected FragmentNfcBinding viewBindingInflate(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, boolean attachToRoot) {
        return FragmentNfcBinding.inflate(inflater, container, attachToRoot);
    }

    @Override
    protected int getLayoutId() {
        return R.layout.fragment_nfc;
    }

    /**
     * @return 返回为 null意为不需要导航栏
     */
    @Override
    protected TitleBar initTitle() {
        return null;
    }

    /**
     * 初始化控件
     */
    @Override
    protected void initViews() {
        mTitleBar.disableLeftView()
        .addAction(new TitleBar.ImageAction(R.drawable.icon_action_query) {
            @Override
            @SingleClick
            public void performAction(View view) {
                openNewPage(SearchComponentFragment.class);
            }
        });
    }
}
`
使用的是XUI模板工程。效果是左边返回按钮没有隐藏，没有添加右边的查询图标。
![1699600847264](https://github.com/xuexiangjys/XUI/assets/48787669/af11f541-a857-420a-936e-c13acc5ea57d)

**Comment by xuexiangjys** [comment]
这是因为你使用的是模板工程, 默认使用的是viewBinding,而非butterknife, 你使用@BindView(R.id.titlebar)是无法获取的组件的,自然initViews里的方法也无法生效
