### ISSUE TITLE
SuperTextView的sShapeCornersRadius属性失效

### ISSUE THREAD

**Issue by doupengfei** [xuexiangjys/XUI#176]
XUI版本：1.2.1
Androdi API>24
SuperTextView的sShapeCornersRadius、sShapeCornersTopLeftRadius、sShapeCornersTopRightRadius、sShapeCornersBottomLeftRadius、sShapeCornersBottomRightRadius皆失效。
设备实机和模拟器都失效。
`<com.xuexiang.xui.widget.textview.supertextview.SuperTextView
                android:id="@+id/super_cb_tv"
                android:layout_width="250dp"
                android:layout_height="60dp"
                android:layout_gravity="center"
                android:layout_marginTop="20dp"
                app:sCenterTextString="选择时间"
                app:sCenterViewGravity="left_center"
                app:sDividerLineType="both"
                app:sLeftIconHeight="40dp"
                app:sLeftIconRes="@drawable/alarm_clock"
                app:sLeftIconWidth="40dp"
                app:sShapeCornersTopLeftRadius="10dp"
                app:sShapeCornersTopRightRadius="10dp" />`
![image](https://github.com/xuexiangjys/XUI/assets/28376640/6c8a0aa5-1a7f-4c64-8bc2-ba22678e680f)

**Comment by xuexiangjys** [comment]
所以是文档没看全呗. 使用sShapeCornersRadius属性, 必须先设置sUseShape为“true”才行
<img width="1063" alt="image" src="https://github.com/xuexiangjys/XUI/assets/15059629/82b8c4e8-8b86-4b73-9a05-3fece3c0bd78">

<img width="639" alt="image" src="https://github.com/xuexiangjys/XUI/assets/15059629/0c91345b-0ca7-4fa7-b056-ed1c0e47525d">
