### ISSUE TITLE
如何让界面最下面的组件，工具，拓展三个Tab选项一直显示

### ISSUE THREAD

**Issue by wyp315360007** [xuexiangjys/XUI#177]
请问一下，XUI这个Demo里最下面的三个功能按钮：组件，工具，拓展能不能一直显示出来。现在demo里面所有的功能按钮点进去以后，下面的这三个按钮都会没有了。

**Comment by xuexiangjys** [comment]
那是因为“组件，工具，拓展”这三个只在主页存在,进去到其他页面,这三个按钮自然会消失.
如果想让三个Tab选项一直显示,那么就需要把这三个Tab选项放到所有页面之上, 独立显示. 或者让他们加载到每个页面之中.
