### ISSUE TITLE
混淆打release包，“shrinkResources true ”  报错：Unable to locate resourceFile ： xui_default_flow_tag_bg_rect_round.xml

### ISSUE THREAD

**Issue by XDChang** [xuexiangjys/XUI#178]
混淆打release包，“shrinkResources true ”  压缩资源文件
报错：
Unable to locate resourceFile (xxx/app/build/intermediates/merged-not-compiled-resources/release/drawable-v17/xui_default_flow_tag_bg_rect_round.xml) in source-sets.

**Comment by XDChang** [comment]
buildTypes {
        release {
            minifyEnabled true
            zipAlignEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

**Comment by XDChang** [comment]
<img width="683" alt="截屏2023-12-12 16 15 23" src="https://github.com/xuexiangjys/XUI/assets/19619335/0c0d5ef4-b1c0-42fa-80dd-6d88499a8896">

**Comment by xuexiangjys** [comment]
clean一下再试试,我这边打包一直都没有问题
<img width="967" alt="image" src="https://github.com/xuexiangjys/XUI/assets/15059629/4e3fffd9-0311-4f2e-9340-3528b6181e7e">
