### ISSUE TITLE
动态生成XRangeSlider实例并添加至Linearlayout时触发空指针

### ISSUE THREAD

**Issue by ghost** [xuexiangjys/XUI#179]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUI/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUI/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/XUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

---

**问题描述（必填）**
在尝试使用代码动态生成一个XRangeSlider实例，并将其添加进Linearlayout布局时，产生空指针错误

**使用的XUI版本（必填）**
1.2.1

**如何重现（必填）**
重现的步骤:
1. 新建一个Activity，在该Activity的xml布局中添加一个没有子组件的Linearlayout，并在Activity通过findViewById等方式绑定到实例上
2. 在Activity内new一个XRangeSlider实例
3. 将该XRangeSlider实例作为linearlayout实例的addView方法参数进行调用
4. 产生错误

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
![image](https://github.com/xuexiangjys/XUI/assets/104063205/ccee98e2-1317-4162-bce5-5a98cffe367b)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: Pixel 2 (AndroidStudio内创建的虚拟机)
 - Android版本:  Android 9.0
 - 设备型号 
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
@AlantSjx 麻烦附上错误日志,方便解决问题
