### ISSUE TITLE
为什么你的app的拓展部分的代码，很难找呢？

### ISSUE THREAD

**Issue by Rgoogle** [xuexiangjys/XUI#180]
你的项目，我真的很艰难的写？安卓的UI部分，真的写的很烦。特别是找你的代码的时候，拓展部分的代码非常的难找，以及工具部分的代码非常的难找。我不知道，给出工具部分和拓展部分的代码有多难。但这确实让人很头疼的事情。

**Comment by xuexiangjys** [comment]
拓展部分本就不属于XUI的内容,很多都是集成的第三方的库,你难找怪我喽?自己不会去搜索?
再说了,我都把相关的开源项目地址都放出来了,你不看怪谁?
