### ISSUE TITLE
ImageLoader清除缓存的问题

### ISSUE THREAD

**Issue by lookather** [xuexiangjys/XUI#184]
ImageLoader的clearCache方法是清除内存和硬盘缓存
但是Glide的清除内存要检查线程是主线程  清除硬盘内存要检查是IO线程  一起执行就会冲突

**Comment by xuexiangjys** [comment]
https://github.com/xuexiangjys/XUI/commit/449bdf230850338b6ba6e32c63512e28e2773c7d
