### ISSUE TITLE
使用沉浸式菜单，标题栏和状态栏重叠了问题？

### ISSUE THREAD

**Issue by qilesoft** [xuexiangjys/XUI#24]
使用StatusBarUtils.translucent(this);后，标题栏和状态栏重叠了问题？请问怎么解决呢，谢谢。

**Comment by xuexiangjys** [comment]
要么你用我的[TitleBar](https://github.com/xuexiangjys/XUI/wiki/ActionBar#titlebar)组件,设置immersive为true，要么使用在xml中使用`android:fitsSystemWindows="true"`。

请不要在issue中问问题！这是我最后一次回复了！详细参考：
https://github.com/xuexiangjys/XUI/issues/25
