### ISSUE TITLE
修改主题无效，看不到效果

### ISSUE THREAD

**Issue by winston1991** [xuexiangjys/XUI#28]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUI/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUI/wiki)，并且确保是框架的问题。

**问题描述**
对问题进行清晰而简明的描述，把握问题的关键点。

**如何重现**
重现的步骤:

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. genymotion]
 - Android版本: [e.g. Android 8.0  api26]
 

**附加信息**
修改AppTheme无效
`    <style name="AppTheme" parent="XUITheme.Phone">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="xui_config_color_background">#44ff0000</item>
        <item name="xui_actionbar_color">@color/colorAccent</item>
    </style>`

**Comment by winston1991** [comment]
![image](https://user-images.githubusercontent.com/6215998/58890436-2f5df980-871d-11e9-9867-d4685c12bde7.png)
初始化Titlebar背景颜色是不是应该从主题中里获取，不应该在color下？

**Comment by xuexiangjys** [comment]
这个只是一个工具类而已,你可以不用这个工具类

**Comment by xuexiangjys** [comment]
已修复,将在下个版本发布.
77487a7f4527ea0274db26dbbfb7a6651289608d
