### ISSUE TITLE
TabBar使用viewpager添加recycleview的点击事件无效

### ISSUE THREAD

**Issue by jcc1014** [xuexiangjys/XUI#32]
**问题描述**
使用TabBar的TabSegment组建配合ViewPager使用，viewpager中使用recycleview加载列表。增加recycleview的点击事件不管用

**如何重现**
重现的步骤:
1. xml中使用TabSegment
2. 定义Viewpager
3. new 一个recycleview加入到viewpager适配器中
4. 增加recycleview的adapter的点击事件不管用

**期望的效果**
recycleview的点击事件管用

**截图**
public class MessageFragment extends BaseFragment {

    @BindView(R.id.tabSegment)
    TabSegment tabSegment;
    @BindView(R.id.mViewPager)
    ViewPager viewPager;
    MessageAdapter adapter;
    RecyclerView recyclerView;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        setContentView(R.layout.fragment_message);
        super.onCreate(savedInstanceState);

    }

    @Override
    public void assignViews(View rootView) {
        ButterKnife.bind(this, rootView);
        intiView();
    }

    private PagerAdapter mPagerAdapter = new PagerAdapter() {
        @Override
        public boolean isViewFromObject(View view, Object object) {
            return view == object;
        }

        @Override
        public int getCount() {
            return 4;
        }

        @Override
        public Object instantiateItem(final ViewGroup container, int position) {

            View view = getPageView(position);
            ViewGroup.LayoutParams params = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
            view.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Log.d("sss","s");
                }
            });
            container.addView(view, params);
            return view;
        }

        @Override
        public void destroyItem(ViewGroup container, int position, Object object) {
            container.removeView((View) object);
        }

    };

    private void intiView(){
        viewPager.setAdapter(mPagerAdapter);
        viewPager.setCurrentItem(0,false);
        tabSegment.addTab(new TabSegment.Tab("内部消息"));
        tabSegment.addTab(new TabSegment.Tab("物业消息"));
        tabSegment.addTab(new TabSegment.Tab("政府消息"));
        tabSegment.addTab(new TabSegment.Tab("系统消息"));
        tabSegment.selectTab(0);
        tabSegment.setMode(TabSegment.MODE_FIXED);
        tabSegment.setupWithViewPager(viewPager,false);
        tabSegment.setSmoothScrollingEnabled(true);
        tabSegment.addOnTabSelectedListener(new TabSegment.OnTabSelectedListener() {
            @Override
            public void onTabSelected(int index) {
                if (tabSegment != null) {
                    tabSegment.hideSignCountView(index);
                }
            }

            @Override
            public void onTabUnselected(int index) {

            }

            @Override
            public void onTabReselected(int index) {
                if (tabSegment != null) {
                    tabSegment.hideSignCountView(index);
                }
            }

            @Override
            public void onDoubleTap(int index) {

            }
        });
    }

    private View getPageView(int position){
        recyclerView = new RecyclerView(getContext());
        List<MessageModel> list = new ArrayList<>(2);
        switch (position){
            case 0:
                list.add(new MessageModel("标题0","1561087968",1,"内容"));
                list.add(new MessageModel("标题0","1561087968",1,"内容"));
                break;
            case 1:
                list.add(new MessageModel("标题1","1561087968",1,"内容1"));
                list.add(new MessageModel("标题1","1561087968",1,"内容1"));
                break;
            case 2:
                list.add(new MessageModel("标题2","1561087968",1,"内容2"));
                list.add(new MessageModel("标题2","1561087968",1,"内容2"));
                break;
            case 3:
                list.add(new MessageModel("标题3","1561087968",1,"内容3"));
                list.add(new MessageModel("标题3","1561087968",1,"内容3"));
                break;
            default:
                break;
        }
        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(getContext());
        adapter = new MessageAdapter(R.layout.message_item,list);
        adapter.setOnItemClickListener(new BaseQuickAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(BaseQuickAdapter adapter, View view, int position) {
                Log.d("s","sssssssss");
            }
        });
        recyclerView.setLayoutManager(linearLayoutManager);
        recyclerView.setAdapter(adapter);
        return recyclerView;
    }

}

**设备信息**
各种设备都不行

**附加信息**

**Comment by xuexiangjys** [comment]
小兄弟,viewpager + recycleview可不是像你这样写的,你这样写明显是有问题的,和组件TabSegment半毛线关系都没有.特地给你改了演示的代码:
e0ecb73b0662348fa947c8f0c92cb5948a99295c
