### ISSUE TITLE
图片选择有问题

### ISSUE THREAD

**Issue by PetrolName** [xuexiangjys/XUI#33]
选择图片，点击拍照图标，拍照完后，在图片列表没有拍照的图片，再拍一张才有上一次拍的照片

**Comment by xuexiangjys** [comment]
请严格按[issue模版](https://github.com/xuexiangjys/XUI/issues/new?assignees=xuexiangjys&labels=bug&template=bug_report.md&title=)要求来填写issue,否则将于2天后自动删除该issue.
