### ISSUE TITLE
TabSegment的showSignCountView没有背景只有数字

### ISSUE THREAD

**Issue by jcc1014** [xuexiangjys/XUI#34]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUI/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUI/wiki)，并且确保是框架的问题。

**问题描述**
使用TagSegement组件是右上角显示signcountview存在问题
**如何重现**
重现的步骤:
1. TabSegment.Tab tab = new TabSegment.Tab("内部消息");
        tab.setSignCountMargin(0, -DensityUtils.dp2px(getContext(), 4));
        tab.showSignCountView(getContext(), 1);
2. tabSegment.addTab(tab);

**期望的效果**
![image](https://user-images.githubusercontent.com/16166779/61511977-11c5c480-aa2b-11e9-87e0-185856a1c84f.png)

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/16166779/61507982-922ff980-aa1a-11e9-9e5e-176e3ae808c0.png)

**Comment by xuexiangjys** [comment]
麻烦仔细阅读使用文档,不可以跳步骤!!!!你这种明显是没有使用XUI的主题!不仅是没背景,你这文字的颜色都不对,字体的大小也不一样

**Comment by jcc1014** [comment]
您好，全局使用主题会和edittext控件冲突，所以都是在每个activity中使用，另外fragement使用xui.inittheme怎么使用文档不是没读过写的太简单了------------------ 原始邮件 ------------------
发件人: "薛翔"<notifications@github.com>
发送时间: 2019年7月20日(星期六) 凌晨0:14
收件人: "xuexiangjys/XUI"<XUI@noreply.github.com>;
抄送: "anthony"<1416119268@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xuexiangjys/XUI] TabSegment的showSignCountView没有背景只有数字 (#34)



麻烦仔细阅读使用文档,不可以跳步骤!!!!你这种明显是没有使用XUI的主题!不仅是没背景,你这文字的颜色都不对,字体的大小也不一样
 
&mdash;

**Comment by xuexiangjys** [comment]
问题已经帮你找出来了，吐槽文档简单你可以不用，没人逼你用。
