### ISSUE TITLE
引入StatefulLayout类时找不到R文件

### ISSUE THREAD

**Issue by winston1991** [xuexiangjys/XUI#35]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUI/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUI/wiki)，并且确保是框架的问题。

**问题描述**
对问题进行清晰而简明的描述，把握问题的关键点。

**如何重现**
重现的步骤:

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
请使用最新版本1.0.7，并保证使用XUI主题，谢谢

**Comment by winston1991** [comment]
还是有问题！ 继承XUITheme.Phone  <style name="MyAppTheme" parent="XUITheme.Phone" />   `  <application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:networkSecurityConfig="@xml/network_security_config"
        android:supportsRtl="true"
        android:theme="@style/MyAppTheme">`

现在报`Error inflating class androidx.appcompat.widget.AppCompatEditText`错误

**Comment by xuexiangjys** [comment]
请使用androidx

**Comment by winston1991** [comment]
用了`    api 'com.github.xuexiangjys:XUI:1.0.7'
    api 'androidx.appcompat:appcompat:1.0.2'
    api 'androidx.core:core:+'
    api 'androidx.recyclerview:recyclerview:1.0.0'
    api 'com.google.android.material:material:1.1.0-alpha07'
    api 'com.github.xuexiangjys.SmartRefreshLayout:refresh-header:1.1.5'
    api 'com.github.xuexiangjys.SmartRefreshLayout:refresh-layout:1.1.5'`

**Comment by winston1991** [comment]
所有的组件都是用的Androidx ,之前一切正常

**Comment by xuexiangjys** [comment]
建议你还是多看看文档，多看看demo是怎么使用的，你那个错误和本库无关

**Comment by winston1991** [comment]
include ':app', ':hk_core'      app  依赖hk_core  Module  
所有的activity 和fragment都放在hk_core里了  这这会不会有影响

**Comment by xuexiangjys** [comment]
androidx和support这两个库是不能共存的

**Comment by winston1991** [comment]
所有 的库全是androidx了

**Comment by winston1991** [comment]
现在是hk_core Module里的styles里没有XUI的theme

**Comment by winston1991** [comment]
只有app  主Module下的values/styles下定义了继承XUI的主题

**Comment by winston1991** [comment]
老大在没？您的demo 我用  android:theme="@style/Theme.AppCompat"也可以跑起来，只是第一次崩溃了
