### ISSUE TITLE
按钮文字不居中，位置稍微偏下一点

### ISSUE THREAD

**Issue by liunewshine** [xuexiangjys/XUI#4]
**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [联想z5 pro]
 - Android版本: [Android 8.1.0]
 - 系统版本（zui10.0）

按钮文字不居中，位置稍微偏下一点
![image](https://user-images.githubusercontent.com/7698511/51399633-5e663b00-1b81-11e9-8105-910a58c538cd.png)

**Comment by xuexiangjys** [comment]
已修复，详细参见：a1f625259b9ee762b15d8c78fe30dddb3d0ed2ee

**Comment by xuexiangjys** [comment]
已修复，详细参见a1f625259b9ee762b15d8c78fe30dddb3d0ed2ee

**Comment by xuexiangjys** [comment]
已修复 @liunewshine

**Comment by xuexiangjys** [comment]
详细参见： a1f625259b9ee762b15d8c78fe30dddb3d0ed2ee
