### ISSUE TITLE
管理员素质何在？

### ISSUE THREAD

**Issue by jiangfan1** [xuexiangjys/XUI#45]
文档不详细，提个问题，就禁言？

**Comment by xuexiangjys** [comment]
没踢你出群就算客气的了，像你这种没有一点礼貌和素养的人请不要玷污开源者的精力。作为一个小白，你什么都不懂就在那么巴拉巴拉讲一堆贬低人的话，你有什么资格评价别人？文档什么的都不看，常见问题也不看，完全都不动脑子，这里不是学校，我也不是你的老师，别给我唧唧歪歪的！
