### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by Cazaea** [xuexiangjys/XUI#47]
版本：1.0.8/1.0.9
国际化语言，应用内手动切换，SmartFreshLayout必须应用重启才能重新渲染Header和Footer,这个问题怎么解决，SmartFreshLayout（看着是1.1.0版本，XUI引用1.1.5超前了？） issues 也看了，无法解决问题；

**Comment by xuexiangjys** [comment]
你的问题并不是XUI的问题. SmartRefreshLayout并不是XUI的内容,你要去下面这个项目里找答案:

https://github.com/scwang90/SmartRefreshLayout

**Comment by Cazaea** [comment]
com.github.xuexiangjys.SmartRefreshLayout:refresh-layout:1.1.5这个是你fork的库吗？

**Comment by xuexiangjys** [comment]
是的

**Comment by Cazaea** [comment]
OK，谢谢，我再看一下~
