### ISSUE TITLE
图片选择模块，预览无法选中图片，一直转圈，无法回调

### ISSUE THREAD

**Issue by winston1991** [xuexiangjys/XUI#48]
**问题描述（必填）**
进入预览界面点击右上角选中该图片，然后点击右下角已完成按钮，会一直显示加载框无回调，不会关闭选择界面，也无法选中图片

**使用的XUI版本（必填）**
com.github.xuexiangjys.PictureSelector:picture-core:1.0.3

**截图**
![RTX截图未命名](https://user-images.githubusercontent.com/6215998/66992453-6ea14b80-f0fc-11e9-8d58-aaadc35b62c4.png)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: 华为p30  genymotion模拟器
 - Android版本: [e.g. Android 7.0]

**附加信息**
进入预览界面点击右上角选中该图片，然后点击右下角已完成按钮，会一直显示加载框无回调，不会关闭选择界面

**Comment by xuexiangjys** [comment]
下载安装演示程序看看，有没有问题

**Comment by winston1991** [comment]
compress（true）时会出现一直转圈，一直在压缩。compress（false）时不会出现转圈，但是在预览界面选中图片，点击完成退到选择图片界面时，图片还是没有选中！

**Comment by xuexiangjys** [comment]
我在我的华为手机6.0、7.0、8.0和9.0上都试过，都是没有问题的，对于这个问题建议你还是先打断点自己找问题

**Comment by xuexiangjys** [comment]
这个是我fork的项目，你可以先去[PictureSelector](https://github.com/LuckSiege/PictureSelector)上看看有没有好的解决方案

**Comment by winston1991** [comment]
PictureSelector这个项目看了，设置.synOrAsy(false)也是没有效果！

**Comment by winston1991** [comment]
我看了PictureSelector的demo代码，同样的代码就出问题了

**Comment by winston1991** [comment]
PictureSelector现在好像不支持androiX

**Comment by winston1991** [comment]
> 我在我的华为手机6.0、7.0、8.0和9.0上都试过，都是没有问题的，对于这个问题建议你还是先打断点自己找问题
是XUI demo示例程序吗？
