### ISSUE TITLE
Fragment 页面上使用两个EditSpinner，后面会把前面一个数据替换

### ISSUE THREAD

**Issue by wubodanran** [xuexiangjys/XUI#5]
![image](https://user-images.githubusercontent.com/29586966/51449568-99c25e80-1d67-11e9-87d0-784fef6d5eb4.png)
当三个按钮来回切换是，配方选中的值会替换更改产线的值.
![image](https://user-images.githubusercontent.com/29586966/51449652-fc1b5f00-1d67-11e9-9588-b53961b5fc65.png)

**Comment by xuexiangjys** [comment]
两个完全独立的控件是不会互相影响的，请检查你的代码是不是控件写错了。我刚才简单地试了你的写法，是没有问题的

**Comment by wubodanran** [comment]
没有，我换了另外一个就没有这个问题了.

**Comment by wubodanran** [comment]
![image](https://user-images.githubusercontent.com/29586966/51450362-70a3cd00-1d6b-11e9-8548-193ed764afa7.png)

![image](https://user-images.githubusercontent.com/29586966/51450376-7f8a7f80-1d6b-11e9-9805-57795d27ba9d.png)

**Comment by xuexiangjys** [comment]
你尝试着把控制代码全删掉，只留下xml去切换tab，如果没有影响，那就是你代码控制的问题

**Comment by xuexiangjys** [comment]
我觉得你还是先打个断点调试一下，明确一下问题再说吧
