### ISSUE TITLE
JPTabBar

### ISSUE THREAD

**Issue by fengyu0114** [xuexiangjys/XUI#53]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUI/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUI/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/XUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

---

**问题描述（必填）**
AndroidStudio 提示找不到JPTabBar组件

**使用的XUI版本（必填）**
implementation 'com.github.xuexiangjys:XUI:1.1.1'

**如何重现（必填）**
重现的步骤:
1. 新建布局xml
2. 创建JPTabBar控件

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
JPTabBar不是XUI的内容
  ```
 //TabBar
    implementation 'com.github.xuexiangjys:JPTabBar:1.0.1'

```

**Comment by fengyu0114** [comment]
好的，感谢回复

---Original---
