### ISSUE TITLE
TitleBar 在10.5寸 实体pad下或者虚拟机触控面积很小、很难点中。 感觉出现偏移

### ISSUE THREAD

**Issue by zhoufengjob** [xuexiangjys/XUI#54]
场景：使用TitleBar  左边action 、中间标题、右边文字action

TitleBar 在10.5寸 实体pad下或者虚拟机下，左边action 图片模式很难点中，图片加文字稍微好点。
右边添加更多action也出现很难点中。

action左边或者右边 触控面积很小、很难点中。 感觉出现偏移

在手机下正常

**Comment by xuexiangjys** [comment]
难点中的话就增加padding,调整到适合点中的大小.

**Comment by yesyeey** [comment]
屏幕分辨率1920*1080 ，横屏， autosize缩放为横屏缩放， getSizeInDp() {
        return 900;
    }；  TitleBar设置.setLeftText("返回").setLeftTextPadding(30, 0)后采可以才可以点击，点击文字可以返回，图标点击返回无效。

**Comment by xuexiangjys** [comment]
参考
https://github.com/xuexiangjys/XUI/commit/1e03faa0357fff1c75339051daf59df6f61b6fcd
