### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by ArvinZJC** [xuexiangjys/XUI#58]
**问题描述**
升级Android Studio 3.6.0（Gradle 5.6.4）后，部分使用XUIGroupListView的项目在编译时出现Android resource linking failed，错误信息：(GRADLE_USER_HOME)\caches\transforms-2\files-2.1\4f4b8f77519e9f06c86146204a335670\jetified-XUI-1.1.2\res\values\values.xml:2647:5-2657:25: AAPT: error: resource attr/xui_orientation (aka com.arvinzjc.xshielder:attr/xui_orientation) not found.

**使用的XUI版本**
1.1.2

**附加信息**
测试发现，出现问题的项目均是Android Gradle Plugin Version==3.6.0， 改为3.5.3就没问题

**Comment by BobEve** [comment]
+1

**Comment by xuexiangjys** [comment]
已经修复好了,过段时间发布,不影响正常使用
e245602b69b96282e41d28fb7658181478c1cca8
