### ISSUE TITLE
XUI 提示 AAPT: error: resource attr/xui_orientation not found.

### ISSUE THREAD

**Issue by emptycupliu** [xuexiangjys/XUI#59]
implementation 'com.github.xuexiangjys:XUI:1.1.2‘

C:\Users\empty\.gradle\caches\transforms-2\files-2.1\e13f4ee319bdd0af9a56576eb0ab6262\jetified-XUI-1.1.1\res\values\values.xml:2462:5-2472:25: **AAPT: error: resource attr/xui_orientation (aka cc.vc22.flowto:attr/xui_orientation) not found.**

使用AS 3.6，之前在未升级之前可用，但升级之后中，就报这个错误。

**Comment by emptycupliu** [comment]
compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 29

改成29，这个问题还是解决不了。

**Comment by BobEve** [comment]
暂时不要升级gradle版本，gradle版本为3.6.0时会出现这个问题 @emptycupliu

**Comment by xuexiangjys** [comment]
同 https://github.com/xuexiangjys/XUI/issues/58?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDcyNzg0NDYxODoxNTA1OTYyOQ%3D%3D#event-3080566638
不要重复提!!!
