### ISSUE TITLE
Dialog 需要还需要引入什么?

### ISSUE THREAD

**Issue by wubodanran** [xuexiangjys/XUI#6]
![image](https://user-images.githubusercontent.com/29586966/51513289-0e1eff80-1e45-11e9-8f97-bdd06f9d3a9d.png)

找不到这个md_btn_positive_selector.

**Comment by xuexiangjys** [comment]
Duplicate https://github.com/xuexiangjys/XUI/issues/1

**Comment by xuexiangjys** [comment]
在1.0.1版本中已修复
