### ISSUE TITLE
华为mate10使用输入框弹窗，经常出现键盘弹不出来。

### ISSUE THREAD

**Issue by KaelInvoker** [xuexiangjys/XUI#63]
依赖版本：   implementation 'com.github.xuexiangjys:XUI:1.1.3'
`在Activity的按钮点击弹出输入框，华为mate10经常出现键盘弹不出来，多次点击才可以弹出来。`
  
`new MaterialDialog.Builder(this)
                .iconRes(R.drawable.icon_tip)
                .title("提示")
                .content("哈哈哈哈哈")
                .inputType(
                        InputType.TYPE_CLASS_TEXT
                                | InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD
                                | InputType.TYPE_TEXT_FLAG_CAP_WORDS)
                .input("哈哈哈哈哈哈哈哈",
                        "",
                        false, new MaterialDialog.InputCallback() {
                            @Override
                            public void onInput(@NonNull MaterialDialog dialog, CharSequence input) {

                            }
                        })
                .positiveText("确定")
                .negativeText("取消")
                .onPositive(((dialog, which) -> {
                    try {
                        registerAccount(dialog);
                    } catch (JSONException e) {
                        e.printStackTrace();
                    }
                }))
                .onNegative(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {

                    }
                })
                .cancelable(false)
                .show();`

**Comment by xuexiangjys** [comment]
建议你发个视频出来,否则我根本看不出是什么个情况

**Comment by xuexiangjys** [comment]
我特地找了一台华为mate10来测了一下，并没有任何问题
