### ISSUE TITLE
bannerlayout不能无限轮播

### ISSUE THREAD

**Issue by tanzhixue** [xuexiangjys/XUI#64]
bannerlayout自动轮播到最后一个之后就不再滚动了
    <com.xuexiang.xui.widget.banner.recycler.BannerLayout
        android:id="@+id/frg_main_bannerLayout"
        android:layout_width="match_parent"
        android:layout_height="150dp"
        android:layout_marginTop="10dp"
        app:bl_autoPlaying="true"
        app:bl_centerScale="1.154"
        app:bl_itemSpace="0dp"
        app:bl_moveSpeed="1.8"
        app:bl_showIndicator="false" />

**Comment by tanzhixue** [comment]
setAdapter后再设置数据不会无限轮播

**Comment by xuexiangjys** [comment]
麻烦按照演示用法来写,数据加载了再调用setAdapter
