### ISSUE TITLE
麻烦在哪里可以看见你的大名，我百度了都找不到你名字，入群又要写名字，晕死

### ISSUE THREAD

**Issue by a1b2c3c** [xuexiangjys/XUI#66]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUI/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUI/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/XUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

---

**问题描述（必填）**
对问题进行清晰而简明的描述，把握问题的关键点。

**使用的XUI版本（必填）**

**如何重现（必填）**
重现的步骤:

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
这点能力都没有,你配做开发?

**Comment by a1b2c3c** [comment]
你百度个名字给我看看，这个和能力有关系？我又不是警察




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "薛翔"<notifications@github.com&gt;; 
发送时间: 2020年5月27日(星期三) 晚上10:24
收件人: "xuexiangjys/XUI"<XUI@noreply.github.com&gt;; 
抄送: "生存的秘密"<264414848@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xuexiangjys/XUI] 麻烦在哪里可以看见你的大名，我百度了都找不到你名字，入群又要写名字，晕死 (#66)





 
这点能力都没有,你配做开发?

**Comment by a1b2c3c** [comment]
是不是写了个开源就牛的说别人配不配?不要以为全世界就你一个人能做开发，我是能力不如你，但是也不是你说配不配的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"薛翔"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月27日(星期三) 晚上10:24
收件人:&nbsp;"xuexiangjys/XUI"<XUI@noreply.github.com&gt;;
抄送:&nbsp;"生存的秘密"<264414848@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xuexiangjys/XUI] 麻烦在哪里可以看见你的大名，我百度了都找不到你名字，入群又要写名字，晕死 (#66)





 
这点能力都没有,你配做开发?
