### ISSUE TITLE
你好,请问dialog的按钮颜色怎么修改？

### ISSUE THREAD

**Issue by tanzhixue** [xuexiangjys/XUI#68]
DialogLoader.getInstance().showConfirmDialog(
                        getContext(),
                        getString(R.string.dialog_delete_collection),
                        getString(R.string.dialog_button_positive),
                        (dialog, which) -> {
                            mPresenter.deleteUserCollectionById(item.getId(), position);
                            dialog.dismiss();
                        },
                        getString(R.string.dialog_button_cancel),
                        (dialog, which) -> dialog.dismiss()
                );

**Comment by xuexiangjys** [comment]
使用`new MaterialDialog.Builder`来构建弹窗，使用下面的api设置按钮的颜色
positiveColor
negativeColor
neutralColor

另外，不要在issue里面问问题，我下次不会回复。
