### ISSUE TITLE
XUI框架里的PictureSelector图片批量选取功能在Android 10系统上无法正常显示和选取图片

### ISSUE THREAD

**Issue by d8qq** [xuexiangjys/XUI#70]
对不起，XUI框架里的PictureSelector图片批量选取功能在Android 10系统上无法正常显示和选取图片，请指教，谢谢您。

**Comment by xuexiangjys** [comment]
PictureSelector不是XUI框架里的内容,详细使用还是以官方为主:
https://github.com/LuckSiege/PictureSelector

**Comment by xuexiangjys** [comment]
除此之外,为了兼容android10,最快的方法就是在application中配置如下属性,开启兼容模式
```
android:requestLegacyExternalStorage="true"
```

**Comment by d8qq** [comment]
好的，用您说的方法，问题已经解决了，谢谢您。
