### ISSUE TITLE
seekBar 在滚动界面，如recycleView里面滑动时，滚动界面会滚动

### ISSUE THREAD

**Issue by renyun2** [xuexiangjys/XUI#71]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUI/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUI/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/XUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

---

**问题描述（必填）seekBar 在滚动界面，如recycleView里面滑动时，滚动界面会滚动，体验不好
对问题进行清晰而简明的描述，把握问题的关键点。

**使用的XUI版本（必填）1.1.4

**如何重现（必填）应重构 dispatchTouchEvent 方法，在滑动时调用
  parent.requestDisallowInterceptTouchEvent(true)不让父组件获取焦点。

重现的步骤:
  override fun dispatchTouchEvent(event: MotionEvent?): Boolean {
        if (event?.action == MotionEvent.ACTION_MOVE) {
            parent.requestDisallowInterceptTouchEvent(true)
        } else {
            parent.requestDisallowInterceptTouchEvent(false)
        }
        return super.dispatchTouchEvent(event)
    }

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
哪个seekBar?

**Comment by renyun2** [comment]
所有seekbar  XSeekBar XRangeSlider 都是这样的情况，放在滚动界面就不好用了。放在边缘滑动时还会触动手势返回，我通过继承 然后在滑动超过10个单位时候调用 parent.requestDisallowInterceptTouchEvent(true) 可以解决问题：

class MyXRangeSlider @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : XRangeSlider(context, attrs, defStyleAttr) {

    private var downX = 0f

    private var isDispatch = false

    @SuppressLint("ClickableViewAccessibility")
    override fun onTouchEvent(event: MotionEvent): Boolean {
        when (event.action) {
            MotionEvent.ACTION_DOWN -> {
                downX = event.x
                isDispatch = false
            }
            MotionEvent.ACTION_MOVE -> {
                if (abs(downX - event.x) > 10f) {
                    isDispatch = true
                }
            }

            MotionEvent.ACTION_UP -> {
                isDispatch = false
            }
        }
        return super.onTouchEvent(event)
    }

    override fun dispatchTouchEvent(event: MotionEvent?): Boolean {
        if (event?.action == MotionEvent.ACTION_MOVE) {
            parent.requestDisallowInterceptTouchEvent(isDispatch)
        } else {
            parent.requestDisallowInterceptTouchEvent(false)
        }
        return super.dispatchTouchEvent(event)
    }
}

**Comment by xuexiangjys** [comment]
已修复
05d9eda27a24cf3119d4239e620666dd88779ec4
