### ISSUE TITLE
SuperTextView布局中无法预览

### ISSUE THREAD

**Issue by minveYu** [xuexiangjys/XUI#74]
如题

**Comment by xuexiangjys** [comment]
https://blog.csdn.net/shaoyezhangliwei/article/details/79621654?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-4.opensearch_close&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromMachineLearnPai2-4.opensearch_close

**Comment by minveYu** [comment]
确实没法预览，布局中supertextview下只有superbutton的提示，没有supertextView？，superButton显示是正常的
