### ISSUE TITLE
ExpandableTextView展开高度不正确，造成屏幕上很大的留白

### ISSUE THREAD

**Issue by RobertCow** [xuexiangjys/XUI#76]
**如题**

**使用的XUI版本（必填）**
com.github.xuexiangjys:XUI:1.1.4

**如何重现（必填）**
重现的步骤:

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/22173894/90592004-19036700-e217-11ea-91d2-d71a1e5d9f36.png)
我的解决办法：
![image](https://user-images.githubusercontent.com/22173894/90598817-5a4f4300-e226-11ea-9012-05631be71d88.png)
![image](https://user-images.githubusercontent.com/22173894/90598940-8f5b9580-e226-11ea-9e57-a8730dca010a.png)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
????
有问题麻烦给出调用的方式和错误的结果,你这么一贴没有任何意义,反正我是没发现什么问题
