### ISSUE TITLE
Dialog的crash问题

### ISSUE THREAD

**Issue by doublefantansy** [xuexiangjys/XUI#8]
com.afollestad.materialdialogs.internal.MDRootLayout cannot be cast to com.xuexiang.xui.widget.dialog.materialdialog.internal.MDRootLayout
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/45680746/53310492-18bb3180-38e8-11e9-9539-1edac96a517c.png">

**Comment by xuexiangjys** [comment]
请使用XUI的时候，不要引入`com.afollestad.material-dialogs`库，因为有部分布局的资源名是相同的

**Comment by doublefantansy** [comment]
哦哦，谢谢
