### ISSUE TITLE
Float types not allowed (at 'default_xui_general_shadow_alpha' with value '0.25').

### ISSUE THREAD

**Issue by blueway** [xuexiangjys/XUI#80]
应该定义
```xml
<attr name="default_xui_general_shadow_alpha" format="float" />
 ```

**Comment by xuexiangjys** [comment]
??? default_xui_general_shadow_alpha 不是属性,你定义attr做啥?
default_xui_general_shadow_alpha 是xui_general_shadow_alpha的默认属性.

**Comment by flyxinhua** [comment]
Float types not allowed (at 'default_xui_general_shadow_alpha' with value '0.25').
Attribute "android:textSize" has already been defined


Android Studio 4.0.1 
buildToolsVersion = '28.0.3'
implementation 'com.github.xuexiangjys:XUI:1.1.5'
