### ISSUE TITLE
好多地方都会崩溃

### ISSUE THREAD

**Issue by taozhixiang** [xuexiangjys/XUI#86]
1.1.5版本，在使用对话框的时候崩溃。
操作步骤：1，引入对应的jar包。 2，按照demo的代码来创建dialog。运行的时候报错，inflater布局的时候出错了。

**Comment by xuexiangjys** [comment]
多看看文档吧:
https://github.com/xuexiangjys/XUI/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#3%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E4%BD%BF%E7%94%A8xui%E4%B8%AD%E7%9A%84%E7%BB%84%E4%BB%B6%E6%97%B6%E4%BC%9A%E6%8A%A5%E9%94%99%E8%AF%B4r%E6%96%87%E4%BB%B6%E6%89%BE%E4%B8%8D%E5%88%B0androidcontentresresourcesnotfoundexception-file-resdrawablexxxxxxml-from-drawable-resource-id-%E5%B1%9E%E6%80%A7%E8%8E%B7%E5%8F%96%E4%B8%8D%E5%88%B0failed-to-resolve-attribute-at-index-%E6%88%96%E8%80%85%E5%B8%83%E5%B1%80%E8%A7%A3%E6%9E%90%E5%87%BA%E9%94%99androidviewinflateexceptionbinary-xml-file-line-xxerror-inflating-class-unknow
