### ISSUE TITLE
ActionBar

### ISSUE THREAD

**Issue by ycyangchun** [xuexiangjys/XUI#89]
返回按钮图片前的区域，点击，不能返回，是什么原因呢

**Comment by xuexiangjys** [comment]
因为你返回按钮前的区域不是可点击区域啊

**Comment by ycyangchun** [comment]
您好，那我怎么设置，扩大点击区域呢，SuperTextView 使用的时，也遇到左侧20dp区域点击无效

**Comment by xuexiangjys** [comment]
https://github.com/xuexiangjys/XUI/blob/master/xui_lib/src/main/java/com/xuexiang/xui/utils/ViewUtils.java#L791

**Comment by ycyangchun** [comment]
您好，点击返回图标前区域，无法返回问题，是由SlideBack 控件引起的
