### ISSUE TITLE
项目里使用的XUI的SuperTextView，但是快速点击会有bug

### ISSUE THREAD

**Issue by myfGitup** [xuexiangjys/XUI#90]
你好，作者，XUI是一个很棒的库，但是我在使用过程中发现一个棘手的问题，我是用SuperTextView 替代线性布局，但是目前是，只要快速点击，SuperTextView 就无法响应点击事件，而且即便能跳转到下一页，也会引起下个页面的Android 原生按钮点击响应不灵敏，经常是点击了好几次都没反应，我追踪了，但是也没找到问题在哪，期待你的回复，可以的话我们可以QQ联系，1041621928 期待你的回复

 implementation 'com.github.xuexiangjys:XUI:1.1.5'

**Comment by xuexiangjys** [comment]
请按照要求填写:
[issue模板](https://github.com/xuexiangjys/XUI/issues/new?assignees=xuexiangjys&labels=bug&template=bug_report.md&title=)
