### ISSUE TITLE
详细问题描述与操作步骤，请作者看下，促进下

### ISSUE THREAD

**Issue by myfGitup** [xuexiangjys/XUI#91]
问题：页面里使用了XUI的superTexteview后导致按钮响应变慢，或者不响应
详细描述：我在fragment的布局里，使用了superTextview ，点击的时候是要跳转到账户与安全页面，我发现每次当我快速点击 
             superTextview的时候，都会导致无法跳转到下一个页面，点击间隔稍微放长一些后，可以跳转，但是，到了新页面，会导 
             致按钮点击不响应，总的来说就是使用superTextview的时候不能快速点击，不然就会不响应，即便响应了，对于新页面里 
              包含superTextview，也会导致按钮响应异常
 截图如下
 fragment
![image](https://user-images.githubusercontent.com/22582151/101846059-1b554c80-3b8b-11eb-8a5e-da3b8784eb7a.png)
账户与安全页面
![image](https://user-images.githubusercontent.com/22582151/101846094-30ca7680-3b8b-11eb-94e0-6f3679349edc.png)
操作视频录屏如下，可以看下
链接：https://pan.baidu.com/s/1bYs1U3sfKSEHybL0m_h5vw 
提取码：q7by 

测试手机：魅族16th,oppo手机，华为mate30,与机型无关，几乎每个手机上快速点击都会出现这个问题，期待回复

**Comment by xuexiangjys** [comment]
你说了一大堆,没有给出任何有效的信息

**Comment by xuexiangjys** [comment]
控件是肯定没有问题的,我都试过了.肯定是你使用的问题

**Comment by myfGitup** [comment]
> 控件是肯定没有问题的,我都试过了.肯定是你使用的问题

控件是正常使用，代码里也是正常的，但是就是存在这个问题，希望作者修复下，关注下，目前解决不了了

**Comment by xuexiangjys** [comment]
我说过了，你没有给任何有效信息，我怎么给你修复，靠猜吗？？？

**Comment by myfGitup** [comment]
已经按照模板写和贴代码录视频了，没有报错，需要提供什么有效信息呢，可以确切点吗

**Comment by myfGitup** [comment]
> 我说过了，你没有给任何有效信息。让你按模板写不写，我怎么给你修复，靠猜吗？？？

已经按照模板写和贴代码录视频了，没有报错，需要提供什么有效信息呢，可以确切点吗

**Comment by xuexiangjys** [comment]
你处理点击事件的逻辑地方啊...

**Comment by myfGitup** [comment]
> 你处理点击事件的逻辑地方啊...
![image](https://user-images.githubusercontent.com/22582151/102075540-5a142c80-3e41-11eb-82ba-ff5a40049017.png)
![image](https://user-images.githubusercontent.com/22582151/102075550-5da7b380-3e41-11eb-935e-6302a9423642.png)
点击事件也是这样写

**Comment by xuexiangjys** [comment]
你有认真看api吗？SuperTextView的点击事件是不能使用@BindView的....

**Comment by xuexiangjys** [comment]
麻烦用`setOnSuperTextViewClickListener`方法，谢谢

**Comment by myfGitup** [comment]
> 你有认真看api吗？SuperTextView的点击事件是不能使用@BindView的....

确实没有找到这个，在Textview的介绍里只看到了SuperTexteview的属性方法，哈哈

**Comment by myfGitup** [comment]
> 麻烦用`setOnSuperTextViewClickListener`方法，谢谢

好的，谢谢作者，这个问题终于要解决了，哈哈，感谢

**Comment by myfGitup** [comment]
> 麻烦用`setOnSuperTextViewClickListener`方法，谢谢

是不是XUI的控件都不能使用@bindView里的@onClick？？

**Comment by xuexiangjys** [comment]
看使用场景啊，@OnClick 对应的是setOnClickListener方法

**Comment by myfGitup** [comment]
> 看使用场景啊，@OnClick 对应的是setOnClickListener方法

嗯嗯，好的，XUI可以配合ButterKnife使用，但是点击事件最好用xUI的，是吧

**Comment by xuexiangjys** [comment]
绝大多数都可以使用@OnClick

**Comment by myfGitup** [comment]
> 绝大多数都可以使用@OnClick

群主大人，现在我的superTextview全部是用XUI里的setOnSuperTextViewClickListener了，但是这个还是会存在点击不灵敏的情况，我观察了下，一定要等到supertextview     的setRightString 和setRightIcon 执行完了，才能响应点击事件
![1](https://user-images.githubusercontent.com/22582151/102159382-65596d80-3ebe-11eb-9b19-9171c4c6d92f.png)
![2](https://user-images.githubusercontent.com/22582151/102159391-68545e00-3ebe-11eb-9f62-64cb87fcd1fa.png)
![3](https://user-images.githubusercontent.com/22582151/102159399-6be7e500-3ebe-11eb-9110-f31716b8109e.png)
![4](https://user-images.githubusercontent.com/22582151/102159407-6ee2d580-3ebe-11eb-9ffb-1f81ecfff318.png)
![5](https://user-images.githubusercontent.com/22582151/102159414-71452f80-3ebe-11eb-9ff8-998287c0e646.png)
