### ISSUE TITLE
SuperTextView中间的EditText怎么设置gravity

### ISSUE THREAD

**Issue by eat-more** [xuexiangjys/XUI#92]
**问题描述（必填）**
想设置SuperTextView中间的输入框向右显示

**使用的XUI版本（必填）**
版本：1.1.5

**如何重现（必填）**
重现的步骤:
在Activity页面使用 superTextView.getCenterEditText().setGravity(Gravity.RIGHT); 无效

**Comment by xuexiangjys** [comment]
你要设置这个做什么？中间的EditText是撑满的，你设置Gravity.RIGHT就是没有用的
