### ISSUE TITLE
考虑新增一个瀑布流

### ISSUE THREAD

**Issue by Lucifer6six** [xuexiangjys/XUI#97]
原声的不好用，产品用需要处理太多高度问题，而且适配也是个头疼的问题

**Comment by xuexiangjys** [comment]
用RecyclerView实现瀑布流不香嘛?什么都不想自己写,干脆你也别做开发得了.

**Comment by Lucifer6six** [comment]
我只是看到了你写的那个流式布局，然后恰巧最近nested +recycle +recycle 多层嵌套后 用Stagger高度问题折磨了很久，就随意说了一句而已
