### ISSUE TITLE
dialog异常

### ISSUE THREAD

**Issue by yanpengqing** [xuexiangjys/XUI#98]
![Screenshot_2021-04-29-10-22-54-052_com.xuexiang.xuidemo.png](https://user-images.githubusercontent.com/17808116/116495294-3378fe80-a8d5-11eb-8eb1-a280d61c39bf.png)
第1和2个点击完全没反应，没弹框
第3,4,5点击出现弹框，但是没有取消和确定按钮。
最后两个正常。
MaterialDialog标签下的都正常

**Comment by xuexiangjys** [comment]
已知问题，在1.1.7上已经修复，近期会进行版本发布
